package carwars.util;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Properties;

public class Settings extends Properties {
	private static final long serialVersionUID = 1L;
	public static final String CONFIG_NAME = "settings/settings.cfg";
	
	private static Settings instance;
	
	private Settings() {
		super();
		this.loadSettings();
	}
	
	private void loadSettings() {
		try{
			FileInputStream is = new FileInputStream(CONFIG_NAME);
			this.load(is);
			is.close();
		} catch(Exception e) {
			this.loadDefault();
		}
	}
	
	private void loadDefault() {
		this.setProperty("game.name", "Car Wars");
		this.setProperty("game.width", "800");
		this.setProperty("game.height", "600");
		this.setProperty("game.gravity", "3");
		this.setProperty("game.terminal_speed", "12");
		this.setProperty("game.anim_speed", "250");
		this.setProperty("game.max_player", "8");
		this.setProperty("game.min_player", "2");
		this.setProperty("game.clouds", "3");
		this.setProperty("game.debug", "false");
		
		this.setProperty("bullet.width", "15");
		this.setProperty("bullet.height", "10");
		
		this.setProperty("car.width", "40");
		this.setProperty("car.height", "30");
		this.setProperty("car.speed", "5");
		this.setProperty("car.max_hp", "100");
		this.setProperty("car.jump_speed", "-3");
		
		this.setProperty("terrain.size", "20");
		
		this.setProperty("udp.buffer_size", "1024");
		this.setProperty("udp.server_port", "4445");
		this.setProperty("udp.client_port", "4446");
		this.setProperty("udp.server_ip", "228.255.255.255");
		
		this.setProperty("tcp.port", "8080");
		this.setProperty("tcp.server_ip", "127.0.0.1");
		
		this.setProperty("assets.dir", 				"assets/");
		this.setProperty("assets.dead_car", 		"sprites/car-dead.png");
		this.setProperty("assets.terrain_sprite", 	"terrain/land-rescale.png");
		this.setProperty("assets.terrain_txt", 		"terrain/maps/terrainI.txt");
		this.setProperty("assets.marker", 			"misc/angle-rescale.png");
		this.setProperty("assets.bullet", 			"sprites/bullet.png");
		this.setProperty("assets.sun", 				"weather/sun.png");
		this.setProperty("assets.cloud", 			"weather/cloud.png");
		this.setProperty("assets.car_sprite", 		"sprites/carI-sprites.png");
		this.setProperty("assets.panel_bg", 		"misc/login-bg2.png");
		this.setProperty("assets.control_bg", 		"misc/howto.png");

		this.setProperty("os.isLinux", "true");
	}
	
	public void saveProperty() {
		try{
			OutputStream os = new FileOutputStream(CONFIG_NAME);
			this.store(os, "Config file. DO NOT EDIT THIS FILE");
			os.close();
		} catch(Exception e) {
			e.printStackTrace();
			System.out.println("Error in saving config.");
		}
	}
	
	public static Settings getInstance() {
		if(instance == null) {
			instance = new Settings();
		}
		
		return instance;
	}
}
